services:
  app:
    image: fs.alacriware
    name: fs.alacriware
    restart: always
    ports:
      - 3030:3030
    volumes:
      - type: bind
        source: /path/on/host
        target: /public