name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # Setting an environment variable with the value of a configuration variable
  username: ${{ vars.ENV_CONTEXT_VAR }} 
  password: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: prepare buildx
      run: docker buildx create --use
    - name: login
      run: docker login --username $username --password-stdin $password
    - name: build docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 --tag windingtherope/fs-alacriware:gh --push . 
