name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare buildx
      run: docker buildx create --use
    - name: build docker image
      run: source BUILDARGS; sh dockerbuild.sh
